name: Generate contribution snake
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate snake
        uses: Platane/snk-action@v1
        with:
          username: ${{ github.repository_owner }}
          output: output/github-contribution-grid-snake.svg
          format: svg
